Crossfire LQ Formats
iNavFlight/inav-configurator pull request #1082
Opened 2020-10-11 18:37 UTC by OptimusTi

This update adds Crsf LQ formats to emulate TBS Hardware and BF format. It also fixes character 234 of clarity_medium and impact_mini fonts.

2020-10-14 09:10 UTC, DzikuVx requested changes
a few nits a we should be ready to go

2020-10-14 09:10 UTC, DzikuVx commented on tabs/osd.js
> +            // enabled: function() {
Please remove unused comments

2020-10-14 09:10 UTC, DzikuVx commented on tabs/osd.js
> +                                    name: 'CRSF_LQ',
formatting seems to be off here

2020-10-14 17:45 UTC, OptimusTi commented on tabs/osd.js
> +                                    name: 'CRSF_LQ',
Changes made on both PR. Thank you!

2020-10-16 08:42 UTC, DzikuVx commented
@OptimusTi there seems to be a conflict with `234` character. Could you merge `master` into your branch and resolve the conflict?

2020-10-16 08:44 UTC, DzikuVx approved these changes

2020-10-16 14:11 UTC, OptimusTi commented
> @OptimusTi there seems to be a conflict with `234` character. Could you merge `master` into your branch and resolve the conflict?

Hello Pawel, done. Thank you again.

2020-10-23 09:01 UTC, merged