Mode in range and Acro indicators
iNavFlight/inav-configurator pull request #1342
Opened 2021-09-10 22:39 UTC by MrD-RC

This adds functionality that shows when a mode is in range, not just currently active on the flight controller.

It also has an indicator to show when ACRO mode would be enabled.

![image](https://user-images.githubusercontent.com/17590174/132924418-8ee9ac4d-1dfd-4821-8755-b14e5000a96d.png)
In this image you can see the 4 indicators on the mode blocks:
- light grey: no ranges
- dark grey: mode range not active
- dark blue: mode range active
- light blue: mode active on flight controller (only changes on save, as with old configurators)

Also in the lower left corner is the ACRO indicator. When acro is enabled it is light blue. Else, it is dark grey. This works based on both active on flight controller and active ranges.

Demo video https://youtu.be/tVq00H0g2Ps

Part fix for #1194

2021-09-22 11:10 UTC, DzikuVx requested changes
Thais is super cool! But you know what @MrD-RC , please make the Acro indicator not looking like a button. People will mistake it for a button and will want to click

2021-09-22 13:14 UTC, MrD-RC commented
Updated the acro indicator to no longer look like a button. It now mimics the ranges.

![image](https://user-images.githubusercontent.com/17590174/134349880-5b68cb3d-d745-4ea2-ad35-cfc7d1d9f19c.png)
![image](https://user-images.githubusercontent.com/17590174/134349924-69fa7934-d55e-440a-b46c-39f68468ce23.png)

I did have it so that just the text changed. But I think it looks better matching the ranges. If this is still too button like, I can change it so that just the text that changes colour.

2021-09-24 11:10 UTC, DzikuVx approved these changes

2021-09-24 11:11 UTC, DzikuVx approved these changes

2021-09-24 11:11 UTC, merged